### ISSUE TITLE
Error: Cannot find module 'shelljs'

### ISSUE THREAD

**Issue by lingyuncelia** [JSREI/ast-hook-for-js-RE#24]
cmd进入K:\ast-hook-for-js-RE-master\ast-hook-for-js-RE-master\src\proxy-server，运行node proxy-server.js。
报错：
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'shelljs'
Require stack:
- K:\ast-hook-for-js-RE-master\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js
- K:\ast-hook-for-js-RE-master\ast-hook-for-js-RE-master\src\proxy-server\rules.js
- K:\ast-hook-for-js-RE-master\ast-hook-for-js-RE-master\src\proxy-server\proxy-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (K:\ast-hook-for-js-RE-master\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (K:\ast-hook-for-js-RE-master\ast-hook-for-js-RE-master\src\proxy-server\rules.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'K:\\ast-hook-for-js-RE-master\\ast-hook-for-js-RE-master\\src\\components\\global-assign-hook-component\\core\\global-assign-hook-component-main.js',
    'K:\\ast-hook-for-js-RE-master\\ast-hook-for-js-RE-master\\src\\proxy-server\\rules.js',
    'K:\\ast-hook-for-js-RE-master\\ast-hook-for-js-RE-master\\src\\proxy-server\\proxy-server.js'
  ]
}

**Comment by lingyuncelia** [comment]
npm install -g XXXXXX，没事，我懂了，原来要全局安装好几个库。

**Comment by youngJL15** [comment]
> npm install -g XXXXXX，没事，我懂了，原来要全局安装好几个库。

我也是遇到这个情况，全局安装好了shelljs，还需要一些什么库呢

**Comment by xiaosass1024** [comment]
> > npm install -g XXXXXX，没事，我懂了，原来要全局安装好几个库。
> 
> 我也是遇到这个情况，全局安装好了shelljs，还需要一些什么库呢

我是在文件夹里面又装了一次shelljs就解决了，全局安装不管用。。
